name: "Build"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:  

jobs:
  Build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Set up dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"
      - name: "Build"
        run: dotnet build --configuration Release
        working-directory: "Source"
      - name: "Get AppSettings.json path"
        id: appSettingsJsonPath
        run: |
          $appSettingsJsonPath = (Get-ChildItem -Filter "AppSettings.json").FullName;
          echo "::set-output name=value::$($appSettingsJsonPath)";
        shell: pwsh
        working-directory: "Source"
      - name: "Convert AppSettings.json to Azure App Service settings"
        id: azureAppServiceSettings
        run: |
          Add-Type -AssemblyName "Project.dll";
          $appSettingsJsonPath = "${{ steps.appSettingsJsonPath.outputs.value }}";

          Write-Host $appSettingsJsonPath;

          Write-Host ${{ steps.appSettingsJsonPath.outputs.value }};
          Write-Host "${{ steps.appSettingsJsonPath.outputs.value }}";

          Write-Host "Irk pirko";






          $azureAppServiceSettings = [Project.ConfigurationHelper]::ConvertToAzureAppServiceSettings($appSettingsJsonPath);
          echo "::set-output name=value::$($azureAppServiceSettings)"
          #echo "::set-output name=value::$('arne')"
        shell: pwsh
        working-directory: "Source/Project/bin/Release/net5.0"
      - name: "Temporary"
        run: Write-Host ${{ steps.azureAppServiceSettings.outputs.value }};
        shell: pwsh