name: "Build"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:  

jobs:
  Build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: "5.0"
      - run: dotnet build --configuration Release
        working-directory: "Source"
      - run: |
          Add-Type -AssemblyName "Project.dll";
          $app = [Project.ConfigurationHelper]::ConvertToAzureAppServiceSettings("/home/runner/work/IdentityServer-Demo-Deploy-NEW/IdentityServer-Demo-Deploy-NEW/Source/AppSettings.json");
          Write-Host $app;
        shell: pwsh
        working-directory: "Source/Project/bin/Release/net5.0"