name: "Build"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:  

jobs:
  Build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: "5.0"
      - run: dotnet build --configuration Release
        working-directory: "Source"
      - run: dir
        working-directory: "Source/Project/bin/Release/net5.0"