name: Arne

on:
  workflow_dispatch:

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "dir in source/application"
        run: dir
        working-directory: "Source/Application"
      - name: "dir (without working-directory)"
        run: dir
      - name: "npm install"
        run: npm install
        working-directory: "Source/Application"
      - name: "dir in source/application"
        run: dir
        working-directory: "Source/Application"
      - name: "Gulp"
        run: gulp
        working-directory: "Source/Application"