name: PowerShell

on:
  workflow_dispatch:

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Display the path"
        run: echo ${env:PATH}
        shell: pwsh
      - name: "Display the path"
        run: |
          $id = get-random
          $code = @"
          using System;
          namespace HelloWorld
          {
            public class Program$id
            {
              public static void Main()
              {
                Console.WriteLine("Hello world!");
              }
            }
          }
          "@
          Add-Type -TypeDefinition $code -Language CSharp;
          iex "[HelloWorld.Program$id]::Main()";
        shell: pwsh