name: PowerShell

on:
  workflow_dispatch:

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Display the path"
        run: echo ${env:PATH}
        shell: pwsh
      - name: "Get location"
        run: Get-Location
        shell: pwsh
      - name: "Get location"
        run: Get-Location
        shell: pwsh
        working-directory: "Source/Project/"