name: PowerShell

on:
  workflow_dispatch:

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Display the path"
        run: echo ${env:PATH}
        shell: pwsh
      - name: "Display the path"
        run: |
          $id = get-random
          $code = @"
          using System;
          namespace HelloWorld
          {
            public class Program$id
            {
              public static string Get(string value)
              {
                return value;
              }
            }
          }
          "@
          Add-Type -TypeDefinition $code -Language CSharp;
          iex '[HelloWorld.Program$id]::Get("Arne")';
        shell: pwsh