name: "Test"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:

env:
  TEST: '[{\u0022a\u0022: "a"}]'

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        run: |
          $test = "${{ env.TEST }}";
          Write-Host $test.GetType();
          Write-Host $test;
        shell: pwsh