name: "Test"

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:

env:
  CONNECTION_STRINGS: >
    [{"name": "IdentityServer", "slotSetting": false, "type": "SQLServer", "value": "Database=${{ secrets.DATABASE_NAME }};Password=${{ secrets.DATABASE_USER_PASSWORD }};Server=${{ secrets.SQLSERVER_NAME }}.database.windows.net;User ID=${{ secrets.DATABASE_USER }}"}]

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        run: |
          $test = '${{ env.CONNECTION_STRINGS }}';
          Write-Host $test.GetType();
          Write-Host $test;
        shell: pwsh